### ISSUE TITLE
DirectGraph.onEdgeTapDown doesn't work for some edges

### ISSUE THREAD

**Issue by mikeryder** [lempiy/flutter_graphite#10]
I am running Graphite 0.3.0, Flutter 2.2.3
I have a graph: 
{id: Step 1, next: [Step 2, Step 2a]}
{id: Step 2, next: [Step 3]}
{id: Step 3, next: []}
{id: Step 2a, next: [Step 3]}

Here is my DirectGraph Widget:
DirectGraph(
                            list: graphData.nodeInputs,
                            cellWidth: 136.0,
                            cellPadding: 24.0,
                            contactEdgesDistance: 10.0,
                            orientation: MatrixOrientation.Vertical,
                            onNodeTapDown: (_, MatrixNode node) => print("Node tap"),
                            onEdgeSecondaryTapDown: (_, Edge edge) => print("Edge tap"),
                            onEdgeTapDown: (_, Edge edge) => print("Edge tap"),
                          )

The graph renders successfully, but the "onEdgeTapDown" does not fire on most taps.  In my example, the edge from "Step 1" to "Step 2" and "Step 2" to "Step 3" never fires.  Sometimes it fires on the edge from "Step 1" to "Step 2a" and "Step 2a" to "Step 3".

Let me know if there is additional information I can provide.

**Comment by lempiy** [comment]
related issue
https://github.com/nateshmbhat/touchable/issues/18
