### ISSUE TITLE
Just a regular click on the edge

### ISSUE THREAD

**Issue by EightRice** [lempiy/flutter_graphite#14]
I see all the gestures you can make on a mobile device, but I'm just looking to click on the edge from the web app. Is there a way to do that?

**Comment by lempiy** [comment]
I haven't tested how it works on web, but you may try to use onEdgeTapDown, onEdgeTapUp. Edges gestures works on top of https://github.com/nateshmbhat/touchable lib.

**Comment by EightRice** [comment]
Yeah, I tried all of them. TapDown is basically a drag that starts above the line and you have to intersect it in order to trigger.
