### ISSUE TITLE
max iteration reached

### ISSUE THREAD

**Issue by EeternalApp** [lempiy/flutter_graphite#23]
can you help me solve this issue.
I have  more than 1000 nodes in DirectGraph then it says max iteration reached.

![WhatsApp Image 2023-04-14 at 1 19 10 AM](https://user-images.githubusercontent.com/130704808/231876177-726ab508-4b06-4895-afc7-5579518dbfd1.jpeg)

**Comment by lempiy** [comment]
Hello!

This limitation will be removed in next minor version (perhaps during this weekend), thanks for report.

**Comment by EeternalApp** [comment]
Thanks !...

**Comment by lempiy** [comment]
release 1.1.1 is live.
