### ISSUE TITLE
InteractiveView error

### ISSUE THREAD

**Issue by sante85** [lempiy/flutter_graphite#5]
Launching lib\main.dart on SM G920F in debug mode...
Running Gradle task 'assembleDebug'...

Compiler message:
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/graphite-0.2.3/lib/graphite_edges.dart:99:18: Error: The method 'InteractiveViewer' isn't defined for the class '_GraphiteEdgesState'.
 - '_GraphiteEdgesState' is from 'package:graphite/graphite_edges.dart' ('/C:/flutter/.pub-cache/hosted/pub.dartlang.org/graphite-0.2.3/lib/graphite_edges.dart').
Try correcting the name to the name of an existing method, or defining a method named 'InteractiveViewer'.
          child: InteractiveViewer(
                 ^^^^^^^^^^^^^^^^^

Compiler message:
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/graphite-0.2.3/lib/graphite_edges.dart:99:18: Error: The method 'InteractiveViewer' isn't defined for the class '_GraphiteEdgesState'.
 - '_GraphiteEdgesState' is from 'package:graphite/graphite_edges.dart' ('/C:/flutter/.pub-cache/hosted/pub.dartlang.org/graphite-0.2.3/lib/graphite_edges.dart').
Try correcting the name to the name of an existing method, or defining a method named 'InteractiveViewer'.
          child: InteractiveViewer(
                 ^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

**Comment by sante85** [comment]
gradle-6.7

**Comment by lempiy** [comment]
@sante85 what flutter version are you using?
