### ISSUE TITLE
Null Safety

### ISSUE THREAD

**Issue by 4mitabh** [lempiy/flutter_graphite#6]
Is there some ongoing work for null safety?
Anything I can contribute to?

**Comment by lempiy** [comment]
@4mitabh I had no time yet to implement flutter 2/new dart features into this lib, if you willing to help feel free to add your PR.

**Comment by hareendranmg** [comment]
Any update?

**Comment by lempiy** [comment]
Depends on [this](https://github.com/quentinleguennec/flutter-arrow-path/pull/3).

**Comment by lempiy** [comment]
@hareendranmg @4mitabh 
`0.3.0-alpha` - with null-safety was prereleased. You can try it and report found issues.

**Comment by hareendranmg** [comment]
@lempiy 👍
